//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataUser:Up_pic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DataUser()
        {
            this.Order = new HashSet<Order>();
        }
    
        public string User_id { get; set; }
        public Nullable<int> Title_id { get; set; }
        public string User_FristName { get; set; }
        public string User_LastName { get; set; }
        public string User_Email { get; set; }
        public string User_Phone { get; set; }
        public byte[] User_Image { get; set; }
        public string Password { get; set; }
        public Nullable<int> Sta_User_id { get; set; }
    
        public virtual StatusUser StatusUser { get; set; }
        public virtual Title Title { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
