//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectEND.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectDEntities : DbContext
    {
        public ProjectDEntities()
            : base("name=ProjectDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<CatePrice> CatePrice { get; set; }
        public virtual DbSet<DataUser> DataUser { get; set; }
        public virtual DbSet<Dormitory> Dormitory { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<PaymentRoomBill> PaymentRoomBill { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<RoomBill> RoomBill { get; set; }
        public virtual DbSet<StatusOrder> StatusOrder { get; set; }
        public virtual DbSet<StatusPayment> StatusPayment { get; set; }
        public virtual DbSet<StatusRoom> StatusRoom { get; set; }
        public virtual DbSet<StatusUser> StatusUser { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Title> Title { get; set; }
        public virtual DbSet<ViewOrder> ViewOrder { get; set; }
        public virtual DbSet<ViewPayBill> ViewPayBill { get; set; }
        public virtual DbSet<ViewPayment> ViewPayment { get; set; }
        public virtual DbSet<ViewUser> ViewUser { get; set; }
    }
}
