//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment:Up_pay
    {
        public int Payment_Id { get; set; }
        public Nullable<int> PaymentOrder_Id { get; set; }
        public Nullable<System.DateTime> Payment_Date { get; set; }
        public byte[] Payment_Pic { get; set; }
        public Nullable<int> StaPay_ID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual StatusPayment StatusPayment { get; set; }
    }
}
