//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentRoomBill:Up_paybill
    {
        public int PaymentBill_Id { get; set; }
        public Nullable<int> PaymentRoomBill_id { get; set; }
        public Nullable<System.DateTime> PaymentBill_date { get; set; }
        public byte[] PaymentPic { get; set; }
        public Nullable<int> StaPayBill_id { get; set; }
    
        public virtual RoomBill RoomBill { get; set; }
        public virtual StatusPayment StatusPayment { get; set; }
    }
}
