//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int Room_id { get; set; }
        public Nullable<int> Room_num { get; set; }
        public Nullable<int> Doc_id { get; set; }
        public Nullable<int> StaRoom_ID { get; set; }
        public Nullable<int> CateP_id { get; set; }
    
        public virtual CatePrice CatePrice { get; set; }
        public virtual Dormitory Dormitory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual StatusRoom StatusRoom { get; set; }
    }
}
