//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomBill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomBill()
        {
            this.PaymentRoomBill = new HashSet<PaymentRoomBill>();
        }
    
        public int RoomBill_Id { get; set; }
        public Nullable<int> Order_Id { get; set; }
        public Nullable<int> Water { get; set; }
        public Nullable<int> Ele { get; set; }
        public Nullable<int> Room_Price { get; set; }
        public Nullable<int> Total_Price { get; set; }
        public Nullable<System.DateTime> Bill_Date_Out { get; set; }
        public Nullable<int> StaBill_id { get; set; }
    
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentRoomBill> PaymentRoomBill { get; set; }
        public virtual StatusOrder StatusOrder { get; set; }
    }
}
