//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectEND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewUser
    {
        public int User_id { get; set; }
        public int Title_id { get; set; }
        public string Title_name { get; set; }
        public string User_FristName { get; set; }
        public string User_LastName { get; set; }
        public string User_Phone { get; set; }
        public string User_Email { get; set; }
        public byte[] User_Image { get; set; }
        public int Sta_User_id { get; set; }
        public string Sta_User_type { get; set; }
    }
}
